### PR TITLE
DMN15-79 Typo in the DMN 1.4 XSD schema (complexType tFilter)

### PR DESCRIPTION
**Pull request by tarilabs**
Issue: https://issues.omg.org/browse/DMN15-79
Proposal: raising

### CODE REVIEW

**Review by falko — APPROVED** [review]
Good catch! I wonder how that got introduced.

**Comment by falko** [comment]
Looks like this was in the original commit https://github.com/omg-dmn-taskforce/omg-dmn-spec/commit/d770e276f2eefd68f4c51a89d9311de6c4255139 . @sringuette you mentioned that you have a Java app to validate the XSDs. Would it be possible to contribute that to this repo so we can run it, e.g. as a GitHub action?

**Comment by SimonRinguette** [comment]
Interesting indeed... I do not have a specific java app to validate the XSD, I just loaded the XSD into the java XSD validator and found the earlier error. However, I'm not sure how this one was not found in the same way.

**Comment by tarilabs** [comment]
I am using the JDK Schema validator.

I can contribute the XSD check ~similarly to what I've introduced in the TCK on suggestion by the TCK group!

**Comment by falko** [comment]
https://www.omg.org/cgi-bin/doc.cgi?dtc/21-11-17 has been updated.

**Pull request merged**
