### PR TITLE
DMN14-190/DMN14-191/DMN14-192/DMN14-193/DMN14-194/DMN14-195 Changes to the diagrams for conditional, filter and iterator boxed expression

### PR DESCRIPTION
**Pull request by SimonRinguette**
Related to XSD changes #14, #15 & #16 
MM change #18

### CODE REVIEW

**Comment by falko** [comment]
Approved in Ballot 5

**Comment by falko** [comment]
@SimonRinguette after discusing and reviewing DMN14-195 with Michelle, I noticed that the proposal text also mentioned adding  the following to `Figure 10.17 Expression class diagram`:

> <i>Add the following abstract class extending</i> Expression
> | Iterator |
> | --- |
> | +iteratorVariable: String |
> 
> *Add the following class extending* Iterator
> | For |
> | --- |
> | |
> 
> *Add the following abstract class extending* Iterator
> | *Quantified* |
> | --- |
> | |
> 
> *Add the following class extending* Quantified
> | Every |
> | --- |
> | |
> 
> *Add the following class extending* Quantified
> | Some |
> | --- |
> | |
> 
> *Add the following class*
> | ChildExpression |
> | --- |
> | +id: ID [0..1] |
> 
> *Add the following class extending* ChildExpression
> | TypedChildExpression |
> | --- |
> | +typeRef: String [0..1] |
> 
>
> <i>Create one aggregation between </i>ChildExpression<i> and
> </i>Expression<i> named </i>value<i> with a cardinality of 1.</i></p>
> 
> <i>Create an aggregation between </i>Iterator and <i>the new
> </i>TypedChildExpression<i> class named “in” with a cardinality
> of 1. </i>
> </p>
> 
> <i>Create an aggregation between </i>For<i> and </i>ChildExpression
> <i>named </i>return<i> with a cardinality of 1.</i></p>
> 
> <i>Create an aggregation between </i>Quantified<i> and
> </i>ChildExpression <i>named </i>satisfies<i> with a cardinality of
> 1.</i></p>

However the only addition to the diagram seems to be the class Iterator:


Am I missing something or should I raise this as an issue to complete the diagram in DMN 1.5?

**Comment by falko** [comment]
@sringuette any feedback regarding this?

**Comment by SimonRinguette** [comment]
In the metamodel, (magic draw) i've created an ExpressionL4 diagram with these details:

image

However, when doing the actual change, these details were not appropriate for the L3 diagram and would not fit on the real estate we had.

If we want these details in the diagram, you can raise an issue to have that diagram integrated in 1.5

**Comment by falko** [comment]
We discussed it in today's RTF meeting and are going to raise an issue to add the diagram in DMN 1.5 as you suggested.

**Pull request merged**
